version: "2"
services:
  wordpress:
    image: wordpress
    links:
      - db:mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DN_NAME: wordpress
    volumes:
    - wp_curso:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wp_pass
    volumes:
    - wp_db_curso:/var/lib/mysql

volumes:
  wp_db_curso:
  wp_curso:
