VAGRANTFILE_API_VERSION = '2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = 'my-server'

  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  config.vm.box = 'chef/ubuntu-14.04'

  #config.vm.network :private_network, type: 'dhcp'
  config.vm.network :private_network, ip: '33.33.33.10'

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|

    chef.run_list = [
      'recipe[my_server]'
    ]
  end
end
